In [1]:
import pandas as pd 

df = pd.read_csv('employee_data.csv')
df

,Index,Employee_ID,Age,Department,Is_Manager,Join_Date,Experience,Salary
0,0,8794,60,Finance,False,1994-03-24,30,238668
1,1,8222,28,Sales,True,1979-12-08,13,105995
2,2,7643,30,Marketing,False,1998-09-25,11,96120
3,3,2737,38,HR,True,2011-11-23,20,153525
4,4,8557,61,HR,True,1976-10-08,31,249192
...,...,...,...,...,...,...,...,...
495,495,8426,32,Marketing,True,2013-12-04,16,126088
496,496,9810,26,IT,True,2022-05-02,15,118094
497,497,5396,34,Finance,False,2025-04-22,16,131208
498,498,7546,60,HR,False,1970-01-13,28,224502
499,499,7744,29,Finance,True,1988-06-21,15,114758

In [2]:
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Index        500 non-null    int64
 1   Employee_ID  500 non-null    int64
 2   Age          500 non-null    int64
 3   Department   500 non-null    object
 4   Is_Manager   500 non-null    bool
 5   Join_Date    500 non-null    object
 6   Experience   500 non-null    int64
 7   Salary       500 non-null    int64
dtypes: bool(1), int64(5), object(2)
memory usage: 24.0+ KB

            Index  Employee_ID         Age  Experience         Salary
count  500.000000   500.000000  500.000000  500.000000     500.000000
mean   249.500000  5440.010000   43.562000   21.316000  170634.372000
std    144.481833  2609.366682   11.857798    6.296621   50611.711724
min      0.000000  1002.000000   22.000000    7.000000   43177.000000
25%    124.750000  3219.000000   34.000000   16.000000  130346.000000
50%    249.500000  5273.500000   44.000000   22.000000  172752.500000
75%    374.250000  7658.000000   52.000000   26.000000  208607.500000
max    499.000000  9981.000000   64.000000   36.000000  293410.000000

In [3]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'])
df.dtypes

Index                   int64
Employee_ID             int64
Age                     int64
Department             object
Is_Manager               bool
Join_Date      datetime64[ns]
Experience              int64
Salary                  int64
dtype: object

In [4]:
df.head()

,Index,Employee_ID,Age,Department,Is_Manager,Join_Date,Experience,Salary
0,0,8794,60,Finance,False,1994-03-24,30,238668
1,1,8222,28,Sales,True,1979-12-08,13,105995
2,2,7643,30,Marketing,False,1998-09-25,11,96120
3,3,2737,38,HR,True,2011-11-23,20,153525
4,4,8557,61,HR,True,1976-10-08,31,249192

In [5]:
# Checking for missing values
df.isnull().sum()

Index          0
Employee_ID    0
Age            0
Department     0
Is_Manager     0
Join_Date      0
Experience     0
Salary         0
dtype: int64

In [6]:
# Checking for duplicate values
df.duplicated().sum()

np.int64(0)

In [7]:
df.to_csv('employee_data1.csv', index=False)

In [8]:
# 1. Average salary by department
df.groupby('Department')['Salary'].mean()

Department
Finance      167374.460784
HR           172150.574713
IT           172650.854545
Marketing    177127.200000
Sales        164615.216981
Name: Salary, dtype: float64

In [10]:
# 2. Total Salary by Department
df.groupby('Department')['Salary'].sum()

Department
Finance      17072195
HR           14977100
IT           18991594
Marketing    16827084
Sales        17449213
Name: Salary, dtype: int64

In [11]:
# 3. Total number of employees in each department
df.groupby('Department')['Employee_ID'].count()

Department
Finance      102
HR            87
IT           110
Marketing     95
Sales        106
Name: Employee_ID, dtype: int64

In [16]:
# 4. Total number of employees
df['Employee_ID'].count()

np.int64(500)

In [17]:
# 5. Average experience by department
df.groupby('Department')['Experience'].mean()

Department
Finance      20.852941
HR           21.459770
IT           21.618182
Marketing    22.126316
Sales        20.603774
Name: Experience, dtype: float64

In [19]:
# 6. Total number of managers
df.groupby('Is_Manager')['Employee_ID'].count()

Is_Manager
False    243
True     257
Name: Employee_ID, dtype: int64

In [21]:
# 7. Minimum salary by department
df.groupby('Department')['Salary'].min()

Department
Finance      75895
HR           69736
IT           65079
Marketing    82230
Sales        43177
Name: Salary, dtype: int64

In [22]:
# 8. Maximum Salary by department
df.groupby('Department')['Salary'].max()

Department
Finance      281861
HR           273400
IT           285886
Marketing    293410
Sales        263818
Name: Salary, dtype: int64