In [15]:
import pandas as pd 
import numpy as np 

df = pd.read_csv('Car_Details.csv')
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [16]:
df.tail()
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 186.6+ KB

              year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [17]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
year,4340.0,2013.090783,4.215344,1992.0,2011.00,2014.0,2016.0,2020.0
selling_price,4340.0,504127.311751,578548.736139,20000.0,208749.75,350000.0,600000.0,8900000.0
km_driven,4340.0,66215.777419,46644.102194,1.0,35000.00,60000.0,90000.0,806599.0

In [18]:
# Check Missing Values
print("Missing Values:")
df.isnull().sum()

Missing Values:

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [19]:
# check Duplicates
print("Duplicate Values Before:")
df.duplicated().sum()

Duplicate Values Before:

np.int64(763)

In [20]:
# Remove Duplicates
df.drop_duplicates(inplace=True)
print("Duplicate Values After:",df.duplicated().sum())

Duplicate Values After: 0

In [21]:
df.dtypes

name             object
year              int64
selling_price     int64
km_driven         int64
fuel             object
seller_type      object
transmission     object
owner            object
dtype: object

In [22]:
# Brand Name 
df['brand'] = df['name'].apply(lambda x: x.split()[0])
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,brand
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,Maruti
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,Maruti
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,Hyundai
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,Datsun
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,Honda

In [23]:
# Encode Categorical Variables
cat_cols = ['fuel', 'seller_type', 'transmission', 'owner']
df = pd.get_dummies(df, columns = cat_cols, drop_first = True)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3577 entries, 0 to 4339
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   name                          3577 non-null   object
 1   year                          3577 non-null   int64
 2   selling_price                 3577 non-null   int64
 3   km_driven                     3577 non-null   int64
 4   brand                         3577 non-null   object
 5   fuel_Diesel                   3577 non-null   bool
 6   fuel_Electric                 3577 non-null   bool
 7   fuel_LPG                      3577 non-null   bool
 8   fuel_Petrol                   3577 non-null   bool
 9   seller_type_Individual        3577 non-null   bool
 10  seller_type_Trustmark Dealer  3577 non-null   bool
 11  transmission_Manual           3577 non-null   bool
 12  owner_Fourth & Above Owner    3577 non-null   bool
 13  owner_Second Owner            3577 non-null   bool
 14  owner_Test Drive Car          3577 non-null   bool
 15  owner_Third Owner             3577 non-null   bool
dtypes: bool(11), int64(3), object(2)
memory usage: 178.2+ KB

In [29]:
df.head()

,name,year,selling_price,km_driven,brand,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti 800 AC,2007,60000,70000,Maruti,False,False,False,True,True,False,True,False,False,False,False
1,Maruti Wagon R LXI Minor,2007,135000,50000,Maruti,False,False,False,True,True,False,True,False,False,False,False
2,Hyundai Verna 1.6 SX,2012,600000,100000,Hyundai,True,False,False,False,True,False,True,False,False,False,False
3,Datsun RediGO T Option,2017,250000,46000,Datsun,False,False,False,True,True,False,True,False,False,False,False
4,Honda Amaze VX i-DTEC,2014,450000,141000,Honda,True,False,False,False,True,False,True,False,True,False,False

In [32]:
df.to_csv('Updated_Car_Details.csv', index=False)